### ISSUE TITLE
Structured dependencies in pkgx.yaml

### ISSUE THREAD

**Issue by dudicoco** [pkgxdev/dev#22]
Currently the dependencies value in `pkgx.yaml` is just a string:
```yaml
dependencies:
  python@3.10 node@16.20.1
env:
  FOO: bar
```

I suggest making it an array so it's more structured and robust:
```yaml
dependencies:
- python@3.10
- node@16.20.1
env:
  FOO: bar
```
